import '../styles/index.css'
import { Inter } from 'next/font/google'

import Header from '@/components/header'
import Footer from '@/components/footer'
import Breadcrumb from '@/components/breadcrumb'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Next Starter 13',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='grid min-h-screen grid-rows-[auto,_1fr,_auto] gap-16'>
					<Header />
					<Breadcrumb size='lg' />
					<main className='relative p-2 md:p-4'>{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	)
}
