import '@/styles/index.css'
import 'prismjs/themes/prism-tomorrow.min.css'
import { Inter } from 'next/font/google'

import Header from '@/components/header'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Bramble Design System',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='wrapper'>
					<Header />
					<main>
						<article data-testid='article'>{children}</article>
					</main>
					<Footer />
				</div>
			</body>
		</html>
	)
}
